/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oop.finalproject;

import java.io.IOException;
import javax.swing.JOptionPane;
import oop.classes.BookingManagement;
import oop.classes.CarManagement;
import oop.classes.CustomerManagement;

/**
 *
 * @author Zeeshan
 */
public class BookCar extends javax.swing.JFrame {

    /**
     * Creates new form BookCar
     */
    public BookCar() {
        initComponents();
        //populate combo boxes with available customer and car data
        this.populateComboBoxes();
    }
    
    public BookCar(String carName) {
        initComponents();
        //populate combo boxes with available customer and car data
        this.populateComboBoxes();
        carName_comboBox.setSelectedItem(carName);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        custName_comboBox = new javax.swing.JComboBox<>();
        carName_comboBox = new javax.swing.JComboBox<>();
        cancel_btn = new javax.swing.JButton();
        bookNow_btn = new javax.swing.JButton();
        customerId_comboBox = new javax.swing.JComboBox<>();
        unbook_btn = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Customer ID");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Customer Name");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Car Name");

        cancel_btn.setText("Cancel");
        cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_btnActionPerformed(evt);
            }
        });

        bookNow_btn.setText("Book Now");
        bookNow_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookNow_btnActionPerformed(evt);
            }
        });

        unbook_btn.setText("UnBook Now");
        unbook_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unbook_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cancel_btn)
                .addGap(73, 73, 73))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bookNow_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(unbook_btn))
                    .addComponent(custName_comboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(carName_comboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customerId_comboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(313, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(customerId_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(custName_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carName_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookNow_btn)
                    .addComponent(unbook_btn))
                .addGap(38, 38, 38)
                .addComponent(cancel_btn)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_btnActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_cancel_btnActionPerformed

    private void bookNow_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookNow_btnActionPerformed
        String customer_id = customerId_comboBox.getSelectedItem().toString();
        String customer_name = custName_comboBox.getSelectedItem().toString();
        String carName = carName_comboBox.getSelectedItem().toString();
        
        //Validator
        if(customer_id.isEmpty()||customer_name.isEmpty()||carName.isEmpty())
            JOptionPane.showMessageDialog(null, "You left any field empty!", "Invalid Input", 1);
        else    //operation
        {
            BookingManagement bookingManage;    //Declaration
            try {       //initialization
                bookingManage = new BookingManagement(customer_id, customer_name, carName);
                if(bookingManage.MakeBooking()){        //making booking
                    //if booking succeded then show positive message
                    JOptionPane.showMessageDialog(null, "Booking made Successfully!");
                    this.setVisible(false);
                }
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "Bookings file Error", 1);
            }
        }
    }//GEN-LAST:event_bookNow_btnActionPerformed

    private void unbook_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unbook_btnActionPerformed
        String customer_id = customerId_comboBox.getSelectedItem().toString();
        String customer_name = custName_comboBox.getSelectedItem().toString();
        String carName = carName_comboBox.getSelectedItem().toString();
        
        //Validator
        if(customer_id.isEmpty()||customer_name.isEmpty()||carName.isEmpty())
            JOptionPane.showMessageDialog(null, "You left any field empty!", "Invalid Input", 1);
        else    //operation
        {
            BookingManagement bookingManage;    //Declaration
            try {       //initialization
                bookingManage = new BookingManagement(customer_id, customer_name, carName);
                if(bookingManage.MakeBooking()){        //making booking
                    //if booking succeded then show positive message
                    JOptionPane.showMessageDialog(null, "Booking made Successfully!");
                    this.setVisible(false);
                }
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "Bookings file Error", 1);
            }
        }
    }//GEN-LAST:event_unbook_btnActionPerformed

    
    //this function will be called in the constructore when car needs to be booked or unbook
    private void populateComboBoxes(){
        //declarations
        CustomerManagement custManage = null;
        CarManagement carManage = null; 
        
        //initializations with handeled exceptions
        try {
            custManage = new CustomerManagement();
            carManage = new CarManagement();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Customer or Car does not Exist!", 2);
        }
        //if no exception occured then proceed next operation
        if(custManage != null && carManage != null)
        {
            //get all customer's id and name 
            String[][] cust_id_name = custManage.getAllCustomers_id_name();
            
            //show all customer id and names into combo box
            for (String[] cust_id_name_found : cust_id_name) {
                customerId_comboBox.addItem(cust_id_name_found[0]);
                custName_comboBox.addItem(cust_id_name_found[1]);
            }
            
            //get all car names
            String[] allCars = carManage.getAllCarNames();
            //show all car names into combo box 
            for(String carName : allCars){
                carName_comboBox.addItem(carName);
            }
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookNow_btn;
    private javax.swing.JButton cancel_btn;
    private javax.swing.JComboBox<String> carName_comboBox;
    private javax.swing.JComboBox<String> custName_comboBox;
    private javax.swing.JComboBox<String> customerId_comboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton unbook_btn;
    // End of variables declaration//GEN-END:variables
}
