/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oop.finalproject;

import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import oop.classes.Car;
import oop.classes.CarManagement;

/**
 *
 * @author Hp
 */
public class CarDetails extends javax.swing.JFrame {

    /**
     * Creates new form CarDetails
     */
    public CarDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        searchByRegNo_btn = new javax.swing.JButton();
        CarRegNo_txtBox = new javax.swing.JTextField();
        searchByName_btn = new javax.swing.JButton();
        CarName_txtBox = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        logOut_btn = new javax.swing.JButton();
        back = new javax.swing.JButton();
        removeCar_btn = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        carDetails_jTable = new javax.swing.JTable();

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        searchByRegNo_btn.setBackground(new java.awt.Color(204, 204, 255));
        searchByRegNo_btn.setForeground(new java.awt.Color(0, 0, 0));
        searchByRegNo_btn.setText("Search RegNo:");
        searchByRegNo_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByRegNo_btnActionPerformed(evt);
            }
        });

        CarRegNo_txtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarRegNo_txtBoxActionPerformed(evt);
            }
        });

        searchByName_btn.setBackground(new java.awt.Color(204, 204, 255));
        searchByName_btn.setForeground(new java.awt.Color(0, 0, 0));
        searchByName_btn.setText("Search Name:");
        searchByName_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByName_btnActionPerformed(evt);
            }
        });

        CarName_txtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarName_txtBoxActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(204, 204, 255));
        jButton6.setForeground(new java.awt.Color(0, 0, 0));
        jButton6.setText("Add");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        logOut_btn.setBackground(new java.awt.Color(204, 204, 255));
        logOut_btn.setForeground(new java.awt.Color(0, 0, 0));
        logOut_btn.setText("Logout");
        logOut_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOut_btnActionPerformed(evt);
            }
        });

        back.setBackground(new java.awt.Color(204, 204, 255));
        back.setForeground(new java.awt.Color(0, 0, 0));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        removeCar_btn.setBackground(new java.awt.Color(204, 204, 255));
        removeCar_btn.setForeground(new java.awt.Color(0, 0, 0));
        removeCar_btn.setText("Remove");
        removeCar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeCar_btnActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(204, 204, 255));
        jButton11.setForeground(new java.awt.Color(0, 0, 0));
        jButton11.setText("Update");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        carDetails_jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Maker", "Name", "Color", "Type", "Seats", "Model", "Condition", "Reg No", "Rent per Hour"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(carDetails_jTable);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(jButton6)
                .addGap(30, 30, 30)
                .addComponent(jButton11)
                .addGap(27, 27, 27)
                .addComponent(removeCar_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                .addComponent(back)
                .addGap(18, 18, 18)
                .addComponent(logOut_btn)
                .addGap(37, 37, 37))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(searchByRegNo_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(searchByName_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CarName_txtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CarRegNo_txtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchByRegNo_btn)
                    .addComponent(CarRegNo_txtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchByName_btn)
                    .addComponent(CarName_txtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logOut_btn)
                    .addComponent(jButton6)
                    .addComponent(removeCar_btn)
                    .addComponent(jButton11)
                    .addComponent(back))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private int id = 0;
    private void searchByRegNo_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByRegNo_btnActionPerformed
        //Search Car by registeration number
        String regNo = CarRegNo_txtBox.getText();
        Car carFound = null;
        try {
            carFound = new CarManagement().FindCar(regNo, true);        //parameter true is passed because car is to find with regNo, if false then carName must be passed
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Cars File Error", 2);
        }
        if(carFound != null){
            //JOptionPane.showMessageDialog(null, "Car Found");
            String[] data = {++id+"", carFound.getMaker(), carFound.getName(), carFound.getCarColor()+"", carFound.getCarType()+"", carFound.getSeatingCapacity(), carFound.getModel(), carFound.getCondition(), carFound.getRegNo(), carFound.getRentPerHour()};
            DefaultTableModel tabelModel = (DefaultTableModel)carDetails_jTable.getModel();
            tabelModel.addRow(data);
        }
        else
            JOptionPane.showMessageDialog(null, "Car Not Found!");
        
        
    }//GEN-LAST:event_searchByRegNo_btnActionPerformed

    private void CarRegNo_txtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarRegNo_txtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CarRegNo_txtBoxActionPerformed

    private void searchByName_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByName_btnActionPerformed
        //Search Car by Name
        String carName = CarName_txtBox.getText();
        Car carFound = null;
        try {
            carFound = new CarManagement().FindCar(carName, false);        //parameter false is passed because car is to find with name, if true then regNo must be passed
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Cars File Error", 2);
        }
        if(carFound != null){
            //JOptionPane.showMessageDialog(null, "Car Found");
            String[] data = {++id+"", carFound.getMaker(), carFound.getName(), carFound.getCarColor()+"", carFound.getCarType()+"", carFound.getSeatingCapacity(), carFound.getModel(), carFound.getCondition(), carFound.getRegNo(), carFound.getRentPerHour()};
            DefaultTableModel tabelModel = (DefaultTableModel)carDetails_jTable.getModel();
            tabelModel.addRow(data);
        }
        else
            JOptionPane.showMessageDialog(null, "Car Not Found!");
        
    }//GEN-LAST:event_searchByName_btnActionPerformed

    private void CarName_txtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarName_txtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CarName_txtBoxActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        AddCar form = new AddCar();
        form.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void logOut_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOut_btnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new LogginForm().setVisible(true);
        
    }//GEN-LAST:event_logOut_btnActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void removeCar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeCar_btnActionPerformed
        // TODO add your handling code here:
        String regNo = JOptionPane.showInputDialog(null,"Enter the Car Reg No to be Removed", "Remove Car", JOptionPane.QUESTION_MESSAGE);
        if(regNo.isEmpty())
            return;
        // else continue removal process
        try {
            CarManagement carManage = new CarManagement();
            //Now call the function to remove
            if(carManage.RemoveCar(regNo))
                JOptionPane.showMessageDialog(null, "Car removed Successfully!");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Cars file Error", 1);
        }
    }//GEN-LAST:event_removeCar_btnActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed

        String regNo = JOptionPane.showInputDialog(null,"Enter The Car Reg No. To Be Updated", "Update Car", JOptionPane.QUESTION_MESSAGE);
        Car carFound = null;
        try {
            carFound = new CarManagement().FindCar(regNo, true);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Cars File Error", 2);
        }
        if(carFound != null){
            JOptionPane.showMessageDialog(null, "Car Updated");
        }
        else
            JOptionPane.showMessageDialog(null, "Car Not Found!");
    }//GEN-LAST:event_jButton11ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CarName_txtBox;
    private javax.swing.JTextField CarRegNo_txtBox;
    private javax.swing.JButton back;
    private javax.swing.JTable carDetails_jTable;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton6;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton logOut_btn;
    private javax.swing.JButton removeCar_btn;
    private javax.swing.JButton searchByName_btn;
    private javax.swing.JButton searchByRegNo_btn;
    // End of variables declaration//GEN-END:variables
}
