/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oop.finalproject;

import java.io.IOException;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import oop.classes.BookingManagement;
import oop.classes.CustomerManagement;
import oop.classes.OwnerManagement;
import oop.classes.Person;

/**
 *
 * @author Hp
 */
public class OwnerDetails extends javax.swing.JFrame {

    /**
     * Creates new form OwnerDetails
     */
    public OwnerDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        searchByName_btn = new javax.swing.JButton();
        searcByName_txtBox = new javax.swing.JTextField();
        searchById_btn = new javax.swing.JButton();
        searchById_txtBox = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        owner_jTable = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        searchByName_btn.setBackground(new java.awt.Color(204, 204, 255));
        searchByName_btn.setForeground(new java.awt.Color(0, 0, 0));
        searchByName_btn.setText("Search Name:");
        searchByName_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByName_btnActionPerformed(evt);
            }
        });

        searcByName_txtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searcByName_txtBoxActionPerformed(evt);
            }
        });

        searchById_btn.setBackground(new java.awt.Color(204, 204, 255));
        searchById_btn.setForeground(new java.awt.Color(0, 0, 0));
        searchById_btn.setText("Search ID:");
        searchById_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchById_btnActionPerformed(evt);
            }
        });

        searchById_txtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchById_txtBoxActionPerformed(evt);
            }
        });

        owner_jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sr#", "ID", "CNIC", "Name", "Contact Number", "Balance"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(owner_jTable);

        jButton6.setBackground(new java.awt.Color(204, 204, 255));
        jButton6.setForeground(new java.awt.Color(0, 0, 0));
        jButton6.setText("Add");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(204, 204, 255));
        jButton7.setForeground(new java.awt.Color(0, 0, 0));
        jButton7.setText("Clear Balance");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(204, 204, 255));
        jButton8.setForeground(new java.awt.Color(0, 0, 0));
        jButton8.setText("Logout");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(204, 204, 255));
        jButton9.setForeground(new java.awt.Color(0, 0, 0));
        jButton9.setText("Back");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(204, 204, 255));
        jButton10.setForeground(new java.awt.Color(0, 0, 0));
        jButton10.setText("Remove");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(204, 204, 255));
        jButton11.setForeground(new java.awt.Color(0, 0, 0));
        jButton11.setText("Update");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(searchByName_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(searchById_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchById_txtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searcByName_txtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jButton7)
                .addGap(147, 147, 147)
                .addComponent(jButton6)
                .addGap(27, 27, 27)
                .addComponent(jButton11)
                .addGap(18, 18, 18)
                .addComponent(jButton10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(jButton9)
                .addGap(18, 18, 18)
                .addComponent(jButton8)
                .addGap(37, 37, 37))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchByName_btn)
                    .addComponent(searcByName_txtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchById_btn)
                    .addComponent(searchById_txtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton7)
                    .addComponent(jButton6)
                    .addComponent(jButton10)
                    .addComponent(jButton11)
                    .addComponent(jButton9))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private int serial = 0;
    private void searchByName_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByName_btnActionPerformed
        //Search Owner by Name
        String ownerName = searcByName_txtBox.getText();
        Person ownerFound = null;
        
        try {
            ownerFound = new OwnerManagement().FindOwner(ownerName, false);        //parameter false is passed because owner is to find with name, if true then cnic must be passed
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Owners File Error", 2);
        }
        if(ownerFound != null){
            BookingManagement bookings = null;
            try {
                 bookings = new BookingManagement();
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
            
            //now create a string array to pass the table to show data
            String[] data = {++serial+"", new Random().nextInt(100)+"", ownerFound.getCnic(), ownerFound.getName()+"", ownerFound.getPhone(), new Random().nextInt(10000)+""};
            DefaultTableModel tabelModel = (DefaultTableModel) owner_jTable.getModel();
            tabelModel.addRow(data);
        }
        else
            JOptionPane.showMessageDialog(null, "Owner Not Found!");

    }//GEN-LAST:event_searchByName_btnActionPerformed

    private void searcByName_txtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searcByName_txtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searcByName_txtBoxActionPerformed

    private void searchById_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchById_btnActionPerformed
        
        //Search owner by cnic
        String ownerCnic = searchById_txtBox.getText();
        
        Person ownerFound = null;
        try {
            ownerFound = new OwnerManagement().FindOwner(ownerCnic, true);        //parameter true is passed because customer is to find with cni, if false then name must be passed
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Owners File Error", 2);
        }
        if(ownerFound != null){
            String[] data = {++serial+"", new Random().nextInt(100)+"", ownerFound.getCnic(), ownerFound.getName()+"", ownerFound.getPhone(), new Random().nextInt(10000)+""};
            DefaultTableModel tabelModel = (DefaultTableModel)owner_jTable.getModel();
            tabelModel.addRow(data);
        }
        else
            JOptionPane.showMessageDialog(null, "Owner Not Found!");

        
        
    }//GEN-LAST:event_searchById_btnActionPerformed

    private void searchById_txtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchById_txtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchById_txtBoxActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:

        AddOwner form = new AddOwner();
        form.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        JOptionPane.showMessageDialog(null, "Balance Cleared!");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        this.setVisible(false);
        new LogginForm().setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        
//        Form1 form = new Form1();
//        form.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        DeleteOwner form = new DeleteOwner();
        form.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        UpdateOwner form = new UpdateOwner();
        form.setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable owner_jTable;
    private javax.swing.JTextField searcByName_txtBox;
    private javax.swing.JButton searchById_btn;
    private javax.swing.JTextField searchById_txtBox;
    private javax.swing.JButton searchByName_btn;
    // End of variables declaration//GEN-END:variables
}
